repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: detect-private-key
      - id: trailing-whitespace
      - id: flake8
        args: [--max-line-length=120]
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [ commit ]
        files: '\.py$'
  - repo: local
    hooks:
      - id: xenon
        name: xenon
        entry: run_xenon.sh
        language: script
        types: [python]
